# Generated by Django 2.0.2 on 2018-08-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Post_date', models.DateTimeField()),
                ('blog_body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
